---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ezepi

ezepi (short for Easy Epidemiology) is a package that simplifies the calculation of common epidemiological measures of occurrence and association from pre-existing datasets, allowing you to get various epi measures from line-list data without wrangling it first.

# How to Install

Run the following commands in your R console to install ezepi:

```
install.packages("devtools")
devtools::install_github("alectries/ezepi")
```

You can update ezepi by running `devtools::update_packages()` and selecting the option for ezepi.

## Basic use

Most ezepi functions follow a basic format:

```
ezepi_function(
  x,              # the dataset to analyze
  exposure_var,   # the categorical exposure variable
  outcome_var,    # the categorical (binary) outcome variable
  person_time,    # the variable noting observation's contributed person-time
  index_exp,      # the value of exposure_var that represents an exposed observation
  ref_exp,        # the value of exposure_var that represents an unexposed observation
  index_out,      # the value of outcome_var that represents a realized outcome
  ref_out,        # the value of outcome_var that represents an unrealized outcome
  conf_lvl        # the confidence level
)
```

Not all of these arguments are used in every function, and many values have defaults. For instance, `person_time` is only included when the function calculates a rate, rate difference, or rate ratio. Additionally, many arguments have default values and do not need to be specified every time: `ref_exp` defaults to 0, and only needs to be set if the referent exposure value is not 0.

ezepi is written to support piping. You can perform data management functions on a dataset before piping it into ezepi without problems.

## Functions

ezepi includes two main types of functions: "ez" functions and "more" functions.

### ez functions

ez functions are used when comparing a binary outcome across a single exposed (or treated, or index) group and a single unexposed (or untreated, or referent) group. Thus, ez functions require you to specify `index_exp`. ez functions include:

1. **ezprev**: Generates a table with counts and prevalence of a specified outcome.
2. **eztbl**: Generates a table with counts, totals, and risks (or odds) of the specified outcome according to exposure status.
3. **ezir**: Generates a table with case counts, total person-time, and rates of the specified outcome according to exposure status.
4. **ezrd**: Generates a table with an estimate, CI, and p-value for a risk difference.
5. **ezrr**: Generates a table with an estimate, CI, and p-value for a risk ratio.
6. **ezior**: Generates a table with an estimate, CI, and p-value for an incidence odds ratio.
7. **ezird**: Generates a table with an estimate, CI, and p-value for an incidence rate difference.
8. **ezirr**: Generates a table with an estimate, CI, and p-value for an indicence rate ratio.

Most ez functions generate a tibble, which can be piped into `View()` or tidyverse functions to extract needed data.

Before version 2.5.0, most ez functions were wrappers of corresponding fmsb functions. From v2.5.0 on, they depend on ezepi::calc.

### more functions

In contrast to ez functions, more functions are used to compare a binary outcome across multiple exposure categories. The exposure variable is assumed to be disjoint. more functions do *not* require you to specify `index_exp`, because all values of `exposure_var` other than `ref_exp` will be considered treatment groups and compared to `ref_exp`. more functions include:

1. **moreprev**: Generates a table with prevalences of a specified outcome.
2. **moretbl**: Generates a table with counts, totals, and risks (or odds) of the specified outcome according to exposure category.
3. **moreir**: Generates a table with case counts, total person-time, and rates of the specified outcome according to exposure category.
4. **morerd**: Generates a table with risk differences, CIs, and p-values for each exposed group compared with the unexposed group.
5. **morerr**: Generates a table with risk ratios, CIs, and p-values for each exposed group compared with the unexposed group.
6. **moreior**: Generates a table with incidence odds ratios, CIs, and p-values for each exposed group compared with the unexposed group.
7. **moreird**: Generates a table with incidence rate differences, CIs, and p-values for each exposed group compared with the unexposed group.
8. **moreirr**: Generates a table with incidence rate ratios, CIs, and p-values for each exposed group compared with the unexposed group.

Before version 2.5.0, most more functions were wrappers of corresponding fmsb functions. From v2.5.0 on, they depend on ezepi::calc.

### mh functions

Like ez functions, mh functions compare a binary outcome across a binary exposed variable. However, it uses a third stratification variable to perform Mantel-Haenszel pooling. mh functions include:

1. **mhrd**: Generates a table with an estimate and Wald CI for a Mantel-Haenszel risk difference.
2. **mhrr**: Generates a table with an estimate and Wald CI for a Mantel-Haenszel risk ratio.
3. **mhior**: Generates a table with an estimate and Wald CI for a Mantel-Haenszel incidence odds ratio.

Before version 2.5.1, all mh functions were wrappers of corresponding fmsb functions. From v2.5.1 on, they depend on ezepi::calc.

### calc

Most of the above functions depend on ezepi's core calculation function: **calc**. calc generates a named vector with four components:

- [1] **estimate**: The estimate of the measure of association specified as `calc`, calc's first argument.
- [2] **lci**: The lower bound of the confidence interval at a confidence level set by `conf_lvl` (default 95%).
- [3] **uci**: The upper bound of the confidence interval at a confidence level set by `conf_lvl` (default 95%).
- [4] **p**: The p-value for the Wald chi-square test performed at a confidence level set by `conf_lvl` (default 95%).

calc accepts a 2x2 contingency table passed as four separate numbers, a 2x2 dataframe (or similar), or a 2x2 matrix. calc assumes (and cannot check!) that you have your exposed cases in the top left corner (`a`), your exposed controls in the top right corner (`b`), your unexposed cases in the bottom left corner (`c`), and your unexposed controls in the bottom right corner (`d`). For rates, calc assumes you have replaced your control counts with person-time sums.

When `n` and `sumdiff` are passed to calc, it produces a weighted estimate of the measure of association, with the standard error multiplied by the design effect (Kish, 1965) to simplify the computation.

### Utility functions

ezepi also includes utility functions that make certain data wrangling tasks easier.

1. **ezt**: An alternative to `base::t()`. Transposes tables but without as many errors and hangups.
2. **mutate_rows**: A wrapper for `dplyr::mutate()` that transposes a table, implements typical mutate arguments, and transposes it again, which allows you to add rows to data as though they were columns.
3. **ezcurve**: Generates a simple epi curve with ggplot. You can add additional ggplot2 functions after the ezcurve call to customize the plot.

## Development status

This package is now in stable condition.

### Coming changes

- Weighted estimation using ez and more functions.

## Legal

Copyright © 2026 Alec Higgins

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
