#' matrix: Build counts frame to pass to calc
#'
#' Not exported. Takes standardized table and generates counts table. This
#' function used to generate a matrix, but doesn't anymore; the name was
#' maintained for consistency.
#'
#' @param x.df A table generated by .standardize.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr pull
#' @importFrom dplyr filter
#' @importFrom dplyr bind_rows
#' @keywords internal

matrix <- function(x.df){
  # setup
  `%>%` <- magrittr::`%>%`

  # generate list of groups through which to iterate
  strata <- as.list(unique(dplyr::pull(x.df, strat)))

  # generate table
  tally.df <- x.df %>%
    dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
    dplyr::filter(out == 'case' | out == 'control') %>%
    dplyr::group_by(exp, out, strat) %>%
    dplyr::tally()

  matrix.list <- list()
  for(i in 1:length(strata)){
    matrix.list[[i]] <- c(
      "a" = dplyr::pull(dplyr::filter(
        tally.df,
        exp == 'exposed' & out == 'case' & strat == strata[[i]]
      ), n),
      "b" = dplyr::pull(dplyr::filter(
        tally.df,
        exp == 'exposed' & out == 'control' & strat == strata[[i]]
      ), n),
      "c" = dplyr::pull(dplyr::filter(
        tally.df,
        exp == 'unexposed' & out == 'case' & strat == strata[[i]]
      ), n),
      "d" = dplyr::pull(dplyr::filter(
        tally.df,
        exp == 'unexposed' & out == 'control' & strat == strata[[i]]
      ), n)
    )
  }

  # bind and return
  matrix.res <- dplyr::bind_rows(matrix.list)
  return(matrix.res)
}
