#' matrix: Build counts matrix to pass to fmsb
#'
#' Not exported. Takes standardized table and generates counts matrix for fmsb Mantel-Haenszel functions.
#'
#' @param x.df A table generated by .standardize.
#' @param index If TRUE, exp is "exposed" or "unexposed". If FALSE, exp could have multiple indexes.
#' @param risk If TRUE, add a risk column. If FALSE, add an odds column. If NA, add prevalence or nothing.
#' @param rate If TRUE, generate a rate table. If FALSE, don't.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr pull
#' @importFrom dplyr filter
#' @importFrom dplyr bind_rows
#' @keywords internal

matrix <- function(x.df, strat_var, index, risk, rate){
  # setup
  `%>%` <- magrittr::`%>%`

  # generate list of groups through which to iterate
  strata <- as.list(unique(dplyr::pull(x.df, strat)))

  # mhrd, mhrr
  ## exp_case, unexp_case, exp_tot, unexp_tot
  if(index & risk & !rate){
    tally.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out, strat) %>%
      dplyr::tally()

    matrix.list <- list()
    for(i in 1:length(strata)){
      matrix.list[[i]] <- c(
        "1" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'exposed' & out == 'case' & strat == strata[[i]]
          ), n),
        "2" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'unexposed' & out == 'case' & strat == strata[[i]]
          ), n),
        "3" = sum(dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'exposed' & !is.na(out) & strat == strata[[i]]
          ), n), na.rm = TRUE),
        "4" = sum(dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'unexposed' & !is.na(out) & strat == strata[[i]]
        ), n), na.rm = TRUE)
      )
    }
  }

  # mhior
  ## exp_case, unexp_case, exp_cont, unexp_cont
  if(index & !risk & !rate){
    tally.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out, strat) %>%
      dplyr::tally()

    matrix.list <- list()
    for(i in 1:length(strata)){
      matrix.list[[i]] <- c(
        "1" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'exposed' & out == 'case' & strat == strata[[i]]
        ), n),
        "2" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'unexposed' & out == 'case' & strat == strata[[i]]
        ), n),
        "3" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'exposed' & out == 'control' & strat == strata[[i]]
        ), n),
        "4" = dplyr::pull(dplyr::filter(
          tally.df,
          exp == 'unexposed' & out == 'control' & strat == strata[[i]]
        ), n)
      )
    }
  }

  # bind and return
  matrix.res <- as.matrix(dplyr::bind_rows(matrix.list))
  return(matrix.res)
}
