#' table: Build counts table to pass to fmsb
#'
#' Not exported. Takes standardized table and generates counts table for fmsb.
#'
#' @param x.df A table generated by .standardize.
#' @param index If TRUE, exp is "exposed" or "unexposed". If FALSE, exp could have multiple indexes.
#' @param risk If TRUE, add a risk column. If FALSE, add an odds column. If NA, add prevalence or nothing.
#' @param rate If TRUE, generate a rate table. If FALSE, don't.
#' @param print Default is FALSE. If TRUE, prints the table to the console.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr tally
#' @importFrom tidyr spread
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr n
#' @importFrom dplyr inner_join
#' @importFrom dplyr join_by
#' @importFrom dplyr ungroup
#' @importFrom tibble add_column
#' @importFrom tidyselect where
#' @keywords internal

table <- function(x.df, index, risk, rate, print = FALSE){
  # setup
  `%>%` <- magrittr::`%>%`

  # ezprev
  if(index & is.na(risk) & !rate){
    table.df <- x.df %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(prevalence = case / total) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # moreprev
  if(!index & is.na(risk) & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(out)) %>%
      dplyr::group_by(out) %>%
      dplyr::tally() %>%
      dplyr::mutate(total = sum(n)) %>%
      dplyr::mutate(prevalence = n / total) %>%
      dplyr::select(-total, -n) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # ezird, ezirr
  if(index & is.na(risk) & rate){
    # generate person-time table
    pt.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp) %>%
      dplyr::select(!out) %>%
      dplyr::summarize(pt = sum(pt))

    # generate counts table
    case.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case') %>%
      dplyr::group_by(exp) %>%
      dplyr::summarize(case = dplyr::n())

    # join tables
    table.df <- case.df %>%
      dplyr::inner_join(pt.df, by = dplyr::join_by(exp)) %>%
      dplyr::mutate(rate = case / pt) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # moreird, moreirr
  if(!index & is.na(risk) & rate){
    # generate person-time table
    pt.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp) %>%
      dplyr::select(!out) %>%
      dplyr::summarize(pt = sum(pt))

    # generate counts table
    case.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case') %>%
      dplyr::group_by(exp) %>%
      dplyr::summarize(case = dplyr::n())

    # join tables
    table.df <- case.df %>%
      dplyr::inner_join(pt.df, by = dplyr::join_by(exp)) %>%
      dplyr::mutate(rate = case / pt) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # ezrd, ezrr
  if(index & risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(risk = case / total) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # morerd, morerr
  if(!index & risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(risk = case / total) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # ezior
  if(index & !risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(odds = case / control) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

  # moreior
  if(!index & !risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(odds = case / control) %>%
      dplyr::ungroup()

    if(print){print(table.df)}
    return(table.df)
  }

}
