#' .table: Build counts table to pass to fmsb
#'
#' Not exported. Takes standardized table and generates counts table for fmsb.
#'
#' @param x.df A table generated by .standardize.
#' @param index If TRUE, exp is "exposed" or "unexposed". If FALSE, exp could have multiple indexes.
#' @param risk If TRUE, add a risk column. If FALSE, add an odds column. If NA, add prevalence or nothing.
#' @param rate If TRUE, generate a rate table. If FALSE, don't.
#' @importFrom magrittr `%>%`
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr tally
#' @importFrom tidyr spread
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom tibble add_column
#' @importFrom tidyselect where
#' @keywords internal

table <- function(x.df, index, risk, rate){
  # setup
  `%>%` <- magrittr::`%>%`

  # ezprev
  if(index & is.na(risk) & !rate){
    table.df <- x.df %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(prevalence = case / total)

    return(table.df)
  }

  # ezird, ezirr
  if(index & is.na(risk) & rate){
    # generate person-time table
    pt.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp) %>%
      dplyr::select(!out) %>%
      dplyr::summarize(pt = sum(pt))

    # generate counts table
    case.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case') %>%
      dplyr::group_by(exp) %>%
      dplyr::summarize(case = n())

    # join tables
    table.df <- case.df %>%
      dplyr::inner_join(pt.df, by = join_by(exp))

    return(table.df)
  }

  # moreird, moreirr
  if(!index & is.na(risk) & rate){
    # generate person-time table
    pt.df <- x.df %>%
      dplyr::filter(is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp) %>%
      dplyr::select(!out) %>%
      dplyr::summarize(pt = sum(pt))

    # generate counts table
    case.df <- x.df %>%
      dplyr::filter(is.na(exp)) %>%
      dplyr::filter(out == 'case') %>%
      dplyr::group_by(exp) %>%
      dplyr::summarize(case = n())

    # join tables
    table.df <- case.df %>%
      dplyr::inner_join(pt.df, by = join_by(exp))

    return(table.df)
  }

  # moreprev
  if(!index & is.na(risk) & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(out)) %>%
      dplyr::group_by(out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      tibble::add_column(out = c("count"), .before = 1) %>%
      ezepi::ezt("out", numeric_data = TRUE) %>%
      dplyr::mutate("total" = sum(count)) %>%
      dplyr::mutate("prevalence" = count / total) %>%
      ezepi::mutate_rows(total = rowSums(dplyr::across(tidyselect::where(is.numeric))), .numeric_data = TRUE) %>%
      dplyr::select(!total)

    return(table.df)
  }

  # ezrd, ezrr
  if(index & risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(risk = case / total)

    return(table.df)
  }

  # morerd, morerr
  if(!index & risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(risk = case / total)

    return(table.df)
  }

  # ezior
  if(index & !risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(exp == 'exposed' | exp == 'unexposed') %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(odds = case / control)

    return(table.df)
  }

  # moreior
  if(!index & !risk & !rate){
    table.df <- x.df %>%
      dplyr::filter(!is.na(exp)) %>%
      dplyr::filter(out == 'case' | out == 'control') %>%
      dplyr::group_by(exp, out) %>%
      dplyr::tally() %>%
      tidyr::spread(out, n) %>%
      dplyr::mutate(total = rowSums(across(everything()))) %>%
      dplyr::mutate(odds = case / control)

    return(table.df)
  }

}
